[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[logger]
level = "info"

[server]
port = 8501
headless = false
runOnSave = true
